# This file configures the static analysis results for your project (errors,
# warnings, and lints).
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: error
    lines_longer_than_80_chars: error
    document_ignores: error
    avoid_print: error

linter:
  rules:
    - public_member_api_docs
    - lines_longer_than_80_chars
    - document_ignores
    - avoid_print
    - prefer_single_quotes
