name: bithacks
description: Collection of bit twiddling hacks. Think _popcnt64 or _pdep_u64.
version: 1.0.0
repository: https://github.com/bramp/bithacks
documentation: https://pub.dev/documentation/bithacks/latest/

topics:
  - bit
  - performance

environment:
  sdk: ^3.2.6

# No dependencies
#dependencies:

dev_dependencies:
  benchmark_harness: ^2.2.2
  format: ^1.4.0
  lints: ^2.1.0
  test: ^1.24.0
