# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache default Dart artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache/
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Format
        run: make format

      - name: Analyze
        run: make analyze

      - name: Run tests
        run: make test-app-ci
